name: unlimiword-prod-pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #  this checks the latest code from the repository to use
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
        # / artifact // this uploads the artifact that it creates, to be downloaded and used by other steps
      - name: Build project
        run: npm run build
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: |
            ./build
            ./package.json

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build
      - name: Debug
        run: |
          pwd
          ls -AlFh
      - name: Run tests
        run: |
           npm install
           npm run test --watchAll=false --rootDir=src

  deploy:
    # add the build as a dependency for this job
    needs: [build, test]
    if: ${{ needs.test.result == 'success'}}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # this token is the secret that we set up and allows github pages to deploy our application
          github_token: ${{ secrets.UNLIMIWORLD_ACCESS_TOKEN }}
          publish_dir: ./build
